# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tz5lJP1_1wVJl1j18lNHabMPn12LX9RK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
import joblib

# Load dataset
data = pd.read_csv("healthcare_data.csv")

print("First 5 Records:")
print(data.head())

# Check missing values
print("\nMissing Values:")
print(data.isnull().sum())

# Feature Selection
features = data[['age','blood_pressure','heart_rate',
                 'glucose_level','hospital_stay_days',
                 'billing_amount']]

# Feature Scaling
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

# Train Isolation Forest
model = IsolationForest(contamination=0.08, random_state=42)
model.fit(scaled_features)

# Predict anomalies
data['anomaly'] = model.predict(scaled_features)

# Convert output (-1 = anomaly, 1 = normal)
data['anomaly'] = data['anomaly'].map({1:0, -1:1})

print("\nAnomaly Counts:")
print(data['anomaly'].value_counts())

# Visualization
plt.figure(figsize=(8,6))
sns.scatterplot(x=data['age'],
                y=data['billing_amount'],
                hue=data['anomaly'],
                palette={0:'blue',1:'red'})

plt.title("Healthcare Data Anomaly Detection")
plt.xlabel("Age")
plt.ylabel("Billing Amount")
plt.legend(title="Anomaly")
plt.show()

# Save Model
joblib.dump(model, "anomaly_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("\nModel saved successfully.")